name: Test
on: 
  pull_request:

jobs:
  test:
    runs-on:
      - codebuild-CodeBuildRunner-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true
      - "image:ubuntu-7.0"
      - "instance-size:small"
    steps:
      - run: whoami
